'use client';

import './globals.css';
import { Inter } from 'next/font/google';
import { PostProvider } from '@/context/PostContext';
import Nav from '@/components/Nav';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Web Dev Blog',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PostProvider>
        <body className={inter.className}>
          <Nav />
          {children}
        </body>
      </PostProvider>
    </html>
  );
}
