'use client';

import { useState } from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import PostContext from '@/context/PostContext';
import Nav from '@/components/Nav';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Web Dev Blog',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const [posts, setPosts] = useState([]);
  return (
    <html lang="en">
      <PostContext.Provider value={{ posts, setPosts }}>
        <body className={inter.className}>
          <Nav posts={posts} />
          {children}
        </body>
      </PostContext.Provider>
    </html>
  );
}
